[View in Colaboratory](https://colab.research.google.com/github/sabumjung/smartfactory/blob/master/02.Autograd_%EC%9E%90%EB%8F%99%EB%AF%B8%EB%B6%84.ipynb)

In [0]:
import torch

In [83]:
x=torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [84]:
y=x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)


In [85]:
#y는 연산의 결과로 생성됨 -> grad_fn을 갖는다.
print(y.grad_fn)

In [86]:
z=y*y*3
out=z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>) tensor(27., grad_fn=<MeanBackward1>)


In [87]:
a=torch.randn(2,2)
a=((a*3)/(a-1))
print(a.requires_grad)

False


In [88]:
a.requires_grad_(True)
print(a.requires_grad)

True


In [90]:
b=(a*a).sum()
print(b.grad_fn)

In [91]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [92]:
x=torch.randn(3, requires_grad=True)
y=x*2
while y.data.norm()<10000:
  y=y+2
print(y)

tensor([5778.7852, 5773.3359, 5774.2944], grad_fn=<AddBackward>)


In [93]:
gradients=torch.tensor([0.1, 1.0, 0.001], dtype=torch.float)
y.backward(gradients)
print(x.grad)

tensor([0.2000, 2.0000, 0.0020])


In [94]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
  print((x**2).requires_grad)

True
True
False
