[View in Colaboratory](https://colab.research.google.com/github/sabumjung/smartfactory/blob/master/Pytorch01.ipynb)

In [1]:
# Default Code
!pip3 install torch torchvision

# Code from Colab
from os import path
from wheel.pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag
platform = '{}{}-{}'.format(get_abbr_impl(), get_impl_ver(), get_abi_tag())

accelerator = 'cu80' if path.exists('/opt/bin/nvidia-smi') else 'cpu'

!pip install -q http://download.pytorch.org/whl/{accelerator}/torch-0.4.0-{platform}-linux_x86_64.whl torchvision
import torch
torch.__version__

    100% |████████████████████████████████| 519.5MB 29kB/s 
tcmalloc: large alloc 1073750016 bytes == 0x59e04000 @  0x7f9266c422a4 0x594e17 0x626104 0x51190a 0x4f5277 0x510c78 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f6070 0x510c78 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f6070 0x4f3338 0x510fb0 0x5119bd 0x4f6070
    100% |████████████████████████████████| 61kB 23.8MB/s 
    100% |████████████████████████████████| 2.0MB 3.8MB/s 
  Found existing installation: Pillow 4.0.0
    Uninstalling Pillow-4.0.0:
      Successfully uninstalled Pillow-4.0.0


'0.3.0.post4'

In [0]:
from __future__ import print_function
import torch

In [60]:
x=torch.empty(5,3)
print(x)
x=torch.rand(5,3)
print(x)
x=torch.zeros(5,3)
print(x)
x=torch.ones(5,3)
print(x)

tensor([[ 4.1389e+00,  3.0771e-41, -7.9990e+33],
        [ 4.5715e-41, -6.0088e+36,  4.5715e-41],
        [-5.6399e+36,  3.0770e-41, -5.6400e+36],
        [ 3.0770e-41, -5.6400e+36,  3.0770e-41],
        [-5.6425e+36,  3.0770e-41, -6.4641e-18]])
tensor([[0.7767, 0.6888, 0.6889],
        [0.2603, 0.3667, 0.6031],
        [0.8667, 0.3058, 0.8026],
        [0.3674, 0.7536, 0.6809],
        [0.8659, 0.5169, 0.8942]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [62]:
x=torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [63]:
# 이 코드는 CUDA가 사용 가능한 환경에서만 실행합니다.
# ``torch.device`` 를 사용하여 tensor를 GPU 안팎으로 이동해보겠습니다.
if torch.cuda.is_available():
    device = torch.device("cuda")          # CUDA 장치 객체(Device Object)로
    y=torch.ones_like(x, device=device)  # GPU 상에 바로(directly) tensor를 생성하거나
    x=x.to("cuda")
    x = x.to(device)                       # 단지 ``.to("cuda")`` 라고만 작성하면 됩니다.
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 는 dtype도 함께 변경합니다!

tensor([6.5000, 4.0000], device='cuda:0')
tensor([6.5000, 4.0000], dtype=torch.float64)


In [64]:
print(x.size())

torch.Size([2])


In [66]:
x=torch.ones(5,3)
y=torch.rand(5,3)
print(y)
print(x+y)

tensor([[0.0641, 0.5784, 0.4522],
        [0.7446, 0.1686, 0.1579],
        [0.8741, 0.9465, 0.8178],
        [0.5066, 0.0355, 0.2703],
        [0.0201, 0.6836, 0.9123]])
tensor([[1.0641, 1.5784, 1.4522],
        [1.7446, 1.1686, 1.1579],
        [1.8741, 1.9465, 1.8178],
        [1.5066, 1.0355, 1.2703],
        [1.0201, 1.6836, 1.9123]])


In [67]:
print(torch.add(x,y))

tensor([[1.0641, 1.5784, 1.4522],
        [1.7446, 1.1686, 1.1579],
        [1.8741, 1.9465, 1.8178],
        [1.5066, 1.0355, 1.2703],
        [1.0201, 1.6836, 1.9123]])


In [69]:
torch.add(x,y,out=result)
print(result)

tensor([[1.0641, 1.5784, 1.4522],
        [1.7446, 1.1686, 1.1579],
        [1.8741, 1.9465, 1.8178],
        [1.5066, 1.0355, 1.2703],
        [1.0201, 1.6836, 1.9123]])


In [70]:
y.add_(x)
print(y)

tensor([[1.0641, 1.5784, 1.4522],
        [1.7446, 1.1686, 1.1579],
        [1.8741, 1.9465, 1.8178],
        [1.5066, 1.0355, 1.2703],
        [1.0201, 1.6836, 1.9123]])


In [71]:
print(x[:,1])

tensor([1., 1., 1., 1., 1.])


In [72]:
print(x[:,2])

tensor([1., 1., 1., 1., 1.])


In [73]:
print(x[:,0])

tensor([1., 1., 1., 1., 1.])


In [75]:
print(x[:,3])

IndexError: ignored

In [77]:
a=torch.ones(5)
print(a)
b=a.numpy()
print(b)
c=torch.from_numpy(b)
print(c)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.])


In [79]:
a.add_(1)
print(a)
print(a.numpy())

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [80]:
if torch.cuda.is_available():
  device=torch.device("cuda")
  y=torch.ones_like(x, device=device)
  x=x.to(device)
  z=x+y
  print(z)
  print(z.to("cpu",torch.double))

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], device='cuda:0')
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], dtype=torch.float64)
